#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "qrcode"
name = "qrcode"
description.en = "Creat and store static and dynamic QR codes"
description.fr = "Créer et stocker des codes QR statiques et dynamiques"

version = "2.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://example.com"
demo = "https://demo.example.com"
admindoc = "https://giandonatoinverso.it/qrcode/documentation/"
code = "https://github.com/giandonatoinverso/PHP-Dynamic-Qr-code"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/giandonatoinverso/PHP-Dynamic-Qr-code/archive/refs/tags/v2.2.zip"
        sha256 = "cb8b6ed893a0552ec54801f7a61a208b38e0860e08ac67d3bead18475c1b816e"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-fpm, php8.2-mysql"

    [resources.database]
    type = "mysql"
